### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by patrickeasters** [lightblue-platform/go-client#1]
This repo doesn't contain any usage examples for this package.

@bserdar do you have any usage examples? Even just a link to a project that uses this package would be helpful.

**Comment by bserdar** [comment]
The http client is a direct port of the Java http client. The usage patterns should be the same, and I even remember testing this against a server at the time, but maybe I am confabulating....

The query/projection building code has plenty of examples in the unit tests.

**Comment by patrickeasters** [comment]
Thanks.  I'll take a look at that.
